# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nS0vyBKNfRYpPteDLMQCDeuZ3fbOEQsY
"""

import sqlite3

conn = sqlite3.connect('my_database.sqlite')
cursor = conn.cursor()

print('hi, are you looking for vote')
response = input("enter Y or N ")
if response=='N':
    print("Thank you")
else:
    aadhar = int(input("Give your adhar number :  "))
    name = input("enter your name : ")
    cursor.execute("SELECT AADHAR from AADHAR where aadhar = ?", (aadhar,))
    #cursor.execute("SELECT NAME from AADHAR where name = ?", (name,))

    rows = cursor.fetchall()
    #print(rows)
    for row in rows:
        if row[0] == aadhar:
            print('aadhar exists')
            break;
    if rows ==[]:
        cursor.execute("INSERT INTO AADHAR (NAME,AADHAR) \
                         VALUES (?, ?)", (name, aadhar))
        print("aadhar added")